name: HTML Validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.2.0
        with:
          root: .
